version: 2.1

on:
  push:
    branches: [feat_tests]
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - store_test_results
      - run:
          name: Build
          command: mvn -B -DskipTests clean package -f ./project-backend
      - run:
          name: Test
          command: mvn test -f ./project-backend
      

orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test