version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/ISA-project/project-backend
    steps:
      - checkout:
        path:  ~/ISA-project
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test